#!/bin/bash

###############################################
# run this script via the 'source' command    #
# e.g. : heat-zurmo-stack-create zurmo-stack  #
###############################################

if [ "$#" -ne 1 ]; then
  echo "Usage: heat-zurmo-stack-create <heat-stack-name>"
  exit
fi

HEAT_STACK_NAME=$1
HEAT_TEMPLATE_URL=https://raw.githubusercontent.com/icclab/cna-seed-project/master/heat/coreos-heat.yaml

PRELOAD_DOCKER_IMAGES=False
ZURMO_START_FLEET_SERVICES=True
NUMBER_WEB_SERVERS=2          # allowed_values: ["2","3","4","5"]
NUMBER_CACHE_SERVERS=3        # allowed_values: ["2","3","4","5"]
ZURMO_GIT_BRANCH=master       # allowed_values: ["master", "logging-dev"]
FLAVOR=m1.medium              # allowed_values: [m1.small, m1.medium, m1.large ]
IMAGE=CoreOS-stable-557.2.0   # allowed_values: [CoreOS-stable-557.2.0, CoreOS-beta-584.0.0, CoreOS-alpha-607.0.0] 
PUBLIC_NET_ID=d57c7d69-a310-4f2c-bddf-4be485c3d399
PRIVATE_NET_ID=4a0888f7-1ca8-480e-9d21-e80dd8564ecd
PRIVATE_SUBNET_ID=22ae589d-b2a5-49c2-bf66-529742d05d16
KEY_NAME_COREOS=brnr_general_rsa

export ETCD_ENDPOINT=`curl https://discovery.etcd.io/new?size=3`

heat stack-create $HEAT_STACK_NAME --template-url $HEAT_TEMPLATE_URL  --parameters "Number of Web Servers=$NUMBER_WEB_SERVERS;Number of Cache Servers=$NUMBER_CACHE_SERVERS;CoreOS Cluster Discovery URL=$ETCD_ENDPOINT;Preload Docker Images=$PRELOAD_DOCKER_IMAGES;Zurmo Start Fleet Services=$ZURMO_START_FLEET_SERVICES;Zurmo Git Branch=$ZURMO_GIT_BRANCH;Flavor=$FLAVOR;Image=$IMAGE;Public Net ID=$PUBLIC_NET_ID;Private Net ID=$PRIVATE_NET_ID;Private Subnet ID=$PRIVATE_SUBNET_ID;Key Name CoreOS=$KEY_NAME_COREOS"