FROM icclabcna/zurmo_log_courier:logging-dev
  
ADD log-courier.toml /etc/confd/conf.d/log-courier.toml
ADD log-courier.conf.tmpl /etc/confd/templates/log-courier.conf.tmpl
ADD log-courier.conf /etc/log-courier.conf
