#!/bin/bash

set -eo pipefail

service rsyslog start

export ETCD_ENDPOINT=${ETCD_ENDPOINT:-10.1.42.1:4001}

echo "[haproxy] booting container"

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD_ENDPOINT -config-file /etc/confd/conf.d/haproxy.toml; do
    echo "[haproxy] waiting for confd to create initial haproxy configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD_ENDPOINT -config-file /etc/confd/conf.d/haproxy.toml &
echo "[haproxy] confd is now monitoring etcd for changes..."

# Start the HAProxy service using the generated config
echo "[haproxy] starting haproxy service..."
service haproxy start

# Start announcing HAProxy to etcd
echo "[haproxy] Start announcing service to etcd"
haproxy-etcd-service-announcer &

tail -f /var/log/haproxy.log