#!/bin/bash

set -eo pipefail

service rsyslog start

export ETCD_PORT=${ETCD_PORT:-4001}
export HOST_IP=${HOST_IP:-10.1.42.1}
export ETCD=$HOST_IP:$ETCD_PORT

echo "[haproxy] booting container. ETCD: $ETCD."

# Try to make initial configuration every 5 seconds until successful
until confd -onetime -node $ETCD -config-file /etc/confd/conf.d/haproxy.toml; do
    echo "[haproxy] waiting for confd to create initial haproxy configuration."
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/haproxy.toml &
echo "[haproxy] confd is now monitoring etcd for changes..."

# Start announcing HAProxy to etcd
echo "[haproxy] Start announcing service to etcd"
haproxy-etcd-service-announcer &

# Start the HAProxy service using the generated config
echo "[haproxy] starting haproxy service..."
service haproxy start

tail -f /var/log/haproxy.log